apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: confluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbitmq
      namespace: confluent
    spec:
      initContainers:
        - name: rabbitmq-config
          image: alpine:latest
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq
          command:
            - "/bin/sh"
          args:
            - "-c"
            - >
              cd /etc/rabbitmq; printf "default_user=admin\ndefault_pass=admin" >> rabbitmq.conf
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources: {}
        env: 
          - name: "RABBITMQ_DEFAULT_USER"
            value: "admin"
          - name: "RABBITMQ_DEFAULT_PASSWORD"
            value: "admin"
        volumeMounts:
          - name: config
            mountPath: "/etc/rabbitmq"
      volumes:
        - name: config
          emptyDir: {}
status: {}
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: confluent
spec:
  ports:
  - name: 5672-5672
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
